<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $fillable = ['slug','name'];

    use Sluggable;
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function cities()
    {
        return $this->hasMany(City::class);
    }

    public function getCitiesCountAttribute()
    {
        return $this->cities->count();
    }

//    public function toArray()
//    {
//        return [
//            'id'=>$this->id,
//            'name'=>$this->name,
//            'city_count'=>$this->cities->count()
//        ]; // TODO: Change the autogenerated stub
//    }

    public function getNameLabelAttribute()
    {
        return ucwords(strtolower($this->name) );
    }
}
